# -*- coding: utf-8 -*-
"""Rollen für das Krimidinner „Der Blutkelch von Schloss Rabenstein“."""

ROLLEN = [
 dict(
  id="stein", nr=1, kern=True, name="Dr. Viktor Stein", alter=54,
  titel="Hausarzt der Familie & Leiter des Sanatoriums am Moor",
  kostuem="Pestarzt: schwarzer Umhang, Schnabelmaske (am Tisch hochgeschoben), schwarze Lederhandschuhe, Arzttasche.",
  oeffentlich="Du bist seit 28 Jahren Hausarzt auf Schloss Rabenstein: gebildet, höflich, stets beherrscht. Das Sanatorium am Moor, das du leitest, wurde mit dem Geld des Grafen gebaut.",
  verhaeltnis="Der Graf ist Patient, Förderer und – so sagt man – dein bester Freund. Zuletzt wirkte er angeschlagen; du hast ihm ein Gichtliniment verschrieben.",
  mörder=True,
  geheimnis="""<b>DU BIST DER MÖRDER.</b> Vor über 25 Jahren, an Halloween 1998, starb Albrecht von Rabenstein, der jüngere Bruder des Grafen, nach einem Abendessen. Du warst ein junger, hochverschuldeter Arzt. Der Graf – der seinen Bruder mit Eisenhut im Blutkelch vergiftet hatte – zahlte dir 50.000 DM, damit du „Herzversagen“ auf den Totenschein schreibst. Seitdem lebst du von seinem Schweigen: Sanatorium, Haus, guter Ruf. Vor drei Tagen sagte dir der Graf: <i>„Zu Halloween beichte ich um Mitternacht. Alles. Auch, wer den Totenschein unterschrieb.“</i> Du hast beschlossen, ihn nicht reden zu lassen.""",
  tat="""<b>Was wirklich geschah:</b> Gegen 21:05 sahst du, wie Baptiste von der Anrichte im Rittersaal weggerufen wurde. Du schlichst hinein und kipptest eine Phiole <b>Eisenhut-Tinktur</b> (Tinctura Aconiti, aus deiner Arzttasche, Apotheke Schwarzmoor) in den Blutkelch. Plötzlich Klirren aus der Küchentür (Berta!). Du erschrakst, stecktest die leere Phiole hinter den Vorhang und flohst durch die Halle. Gegen 21:15 schautest du kurz bei Madame Zora im Kaminzimmer vorbei, nur um „irgendwo gewesen zu sein“, bliebst drei Minuten und zogst in der Halle hastig die Handschuhe aus.""",
  abend_wahr="Siehe „Was wirklich geschah“.",
  abend_version="„Ich war ab kurz nach 21:00 bis zum Toast bei Madame Zora im Kaminzimmer. Wir sprachen über die Séance.“",
  beobachtung=[
   "Du weißt als Arzt: Aconitin wirkt nach 10 bis 60 Minuten, und Rotwein überdeckt den bitteren Geschmack. Dein Alibi (Zora) ist dünn: Sie weiß, dass du erst gegen 21:15 kamst.",
   "Gegen 21:19 hat dich in der Halle Rosalie (falls anwesend) gesehen, als du die Handschuhe wegsteckstest. Und Berta hat in der Küche „etwas“ gehört. Du weißt nicht, was sie gesehen haben.",
  ],
  runde2="""<b>Deine Risiken:</b> Zora kann bezeugen, dass du erst gegen 21:15 kamst. Edgar sah durch die Glastür einen Schatten mit Schnabel. Berta sah schwarze Handschuhe. Rosalie sah, wie du Handschuhe wegsteckst. Die Phiole stammt von einem Arzt. <b>Deine Strategie:</b> Lenke den Verdacht auf Lucian (Streit, Schulden), Morgana (Erbe), Berta (drohte laut) oder Jack und Zora („Eisenhut gibt es im Gewächshaus und in Zoras Koffer“). Wenn Zora widerspricht: „Im Trancezustand verliert ein Medium jedes Zeitgefühl.“ Wenn der Totenschein auftaucht: „Ich habe damals nach bestem Wissen unterschrieben.“""",
  ziel="Nicht überführt werden. Bestes Ergebnis: Die Gruppe beschuldigt jemand anderen. Du darfst lügen, solange es zur Rolle passt. Wenn du eindeutig überführt bist, gestehe mit Stil (ein Monolog ist erlaubt).",
  motiv_kurz="Der Graf wollte um Mitternacht beichten und ihn als Komplizen von 1998 nennen.",
 ),
 dict(
  id="zora", nr=2, kern=True, name="Madame Zora Nacht", alter=49,
  titel="Medium & Geisterbeschwörerin",
  kostuem="Wahrsagerin: Turban oder Schleier, viele Schals und Ketten, Kristallkugel oder Tarotkarten.",
  oeffentlich="Du bist die berühmteste Geisterbeschwörerin im Umkreis von hundert Meilen. Heute Abend leitest du die Séance, die kurz nach dem Toast beginnt.",
  verhaeltnis="Der Graf hat dich für diesen Abend engagiert (5.000 €). Er möchte mit dem Geist seines verstorbenen Bruders Albrecht sprechen.",
  geheimnis="""Du bist eine <b>Betrügerin</b>. Die Geisterklopfzeichen, der kalte Hauch, die schwebende Glocke: alles Tricks (Fäden, Magnete, Nebelgerät, versteckter Lautsprecher). Niemand darf das erfahren, sonst ist dein Ruf ruiniert. Zudem vertraute dir der Graf vor dem Essen an: <i>„Ich habe Albrecht auf dem Gewissen, Zora. Ich muss ihn um Verzeihung bitten, bevor es zu spät ist.“</i> Du weißt also, dass der Graf etwas gestehen wollte.""",
  abend_wahr="21:00 bis 21:30 allein im Kaminzimmer. Du hast Kerzen, Fäden und das Nebelgerät vorbereitet. Gegen <b>21:15</b> kam Dr. Stein vorbei: atemlos, mit schwarzen Lederhandschuhen, ein bitter-medizinischer Geruch. Er sagte: „Ich wurde aufgehalten“, blieb etwa drei Minuten und ging wieder.",
  abend_version="Die Wahrheit: Du warst im Kaminzimmer und hast die Séance vorbereitet. Was genau du dort getan hast, verschweigst du („Ich sammelte Energie und rief die Geister“).",
  beobachtung=[
   "<b>Dr. Stein erschien erst gegen 21:15</b> (nicht früher!), trug schwarze Lederhandschuhe, roch bitter-medizinisch und wirkte gehetzt. Er blieb nur etwa drei Minuten.",
   "Der Graf sagte dir vor dem Essen: <i>„Ich habe Albrecht auf dem Gewissen. Ich muss ihn um Verzeihung bitten.“</i> (Nenne das spätestens in Runde 2.)",
   "Um 21:35 hast du <b>absichtlich</b> alle Kerzen ausgeblasen, weil die Séance begann. Die Dunkelheit kam von dir, nicht vom Mörder.",
   "Dein Séance-Koffer enthält ein Bündel getrocknete Eisenhutwurzel („Hexenwurz“) als Nebel-Requisite. Es ist original verschnürt und unangetastet.",
  ],
  runde2="Wenn Stein behauptet, er sei die ganze Zeit bei dir gewesen, widersprich deutlich, aber im Stil einer Geisterbeschwörerin. Wenn man dich in die Enge treibt, darfst du deine Tricks gestehen: Besser als Betrügerin dastehen als als Mörderin.",
  ziel="Den Mörder finden und deinen Ruf retten. Sprich in Rätseln, werde aber konkret, wenn es zählt.",
  motiv_kurz="Falls der Graf ihre Tricks durchschaut hätte, wäre ihr Ruf zerstört. Verdächtig durch die Eisenhutwurzel im Koffer.",
 ),
 dict(
  id="edgar", nr=3, kern=True, name="Sir Edgar Blackwood", alter=58,
  titel="Industrieller & Geschäftspartner des Grafen",
  kostuem="Zombie-Manager: zerrissener Anzug, Kunstblut am Kragen, Aktentasche.",
  oeffentlich="Selfmade-Millionär, laut und jovial. Dir gehört Blackwood Industries. Dein Lieblingssatz: „Zeit ist Geld.“",
  verhaeltnis="Seit 20 Jahren Geschäftspartner und Jagdfreund des Grafen. Der Graf hat deine Firma über die Jahre mit Darlehen gestützt.",
  geheimnis="""Deine Firma ist praktisch <b>pleite</b>. Heute Nachmittag hast du den Grafen um 2 Millionen Euro Überbrückungskredit gebeten. Er lehnte ab und kündigte an, seine bisherigen Darlehen zum Jahresende fällig zu stellen. Niemand weiß, dass du am Ende bist: weder deine Frau noch deine Bank.""",
  abend_wahr="21:00 bis 21:20 allein auf der <b>Terrasse</b>. Du telefonierst flüsternd mit deinem Anwalt über eine mögliche Insolvenz. Die Terrasse hat Glastüren zum Rittersaal.",
  abend_version="„Ich war auf der Terrasse und habe mit meiner Frau telefoniert.“ (Der Ort stimmt, den Gesprächspartner verschweigst du.)",
  beobachtung=[
   "Gegen <b>21:10</b> hast du durch die Glastür in den Rittersaal geschaut. Im Kerzenlicht fiel der <b>Schatten einer Gestalt mit langem Umhang und langem, spitzem Schnabel</b> an die Wand, an der Anrichte, nahe beim Blutkelch. Du hast dir nichts dabei gedacht (es ist Halloween!). Das Gesicht hast du nicht gesehen.",
   "Auf der Terrasse war außer dir <b>niemand</b>. Du hättest jeden gesehen, der hinaustrat.",
   "Der Graf war am Nachmittag „ungewöhnlich weich und nachdenklich“.",
  ],
  runde2="Die Beobachtung mit dem Schnabel erzählst du spätestens in der Zeugenrunde. Wenn jemand fragt, warum du bisher geschwiegen hast: „Ich hielt es für ein Kostüm.“",
  ziel="Den Mörder finden und dein Geheimnis (Pleite) hüten. Du darfst auf Nachfrage zugeben, dass der Kredit abgelehnt wurde. Das Ausmaß bleibt geheim.",
  motiv_kurz="Der Graf lehnte den Kredit ab und wollte die Darlehen fällig stellen. Edgar wäre ruiniert.",
 ),
 dict(
  id="berta", nr=4, kern=True, name="Berta Knochen", alter=61,
  titel="Köchin von Schloss Rabenstein",
  kostuem="Skelett-Schürze (Knochen-Print), Kochhaube, Kochlöffel.",
  oeffentlich="Resolut, direkt, 35 Jahre im Dienst. Du kochst das Bankett persönlich. Heute Nachmittag gab es einen lauten Streit mit dem Grafen, den alle hörten. Du riefst: „Das werden Sie bereuen!“",
  verhaeltnis="Der Graf hat dir nach 35 Jahren wegen „zu teurer Zutaten“ fristlos gekündigt, ohne Pension.",
  geheimnis="""Du hast <b>1998</b> gesehen, was an jenem Halloween-Abend geschah: Der Graf füllte den Blutkelch für seinen Bruder Albrecht höchstpersönlich nach und brachte ihn ihm mit den Worten „Auf die Familie!“. Albrecht trank und brach zusammen. Du hast geschwiegen – aus Angst um deine Stelle. Dieses Schweigen quält dich seit über 25 Jahren.""",
  abend_wahr="Du warst in der Küche, aber um etwa <b>21:09</b> gingst du durch die Schwingtür zum Rittersaal, um Dessertteller zu holen. Du sahst eine Gestalt in <b>schwarzem Umhang mit schwarzen Handschuhen</b> über dem Blutkelch gebeugt. Glas klirrte. Du erschrakst und ließest das Tablett fallen. Die Gestalt floh durch die Halle. Es roch bitter-medizinisch, „wie Franzbranntwein“. Ein Gesicht hast du nicht gesehen, nur den Rücken.",
  abend_version="„Ich war die ganze Zeit in der Küche bei den Töpfen.“ (Du willst nicht zugeben, im Rittersaal gewesen zu sein: Wegen deiner Drohung würde man dich verdächtigen.)",
  beobachtung=[
   "<b>21:09:</b> schwarzer Umhang, schwarze Handschuhe, Gestalt über dem Blutkelch, Glasklirren, bitterer Medizingeruch. Rücken, kein Gesicht.",
   "Das Klirren, das manche gehört haben, war dein Tablett.",
  ],
  runde2="Wenn man dich direkt fragt („Hast du jemanden an der Anrichte gesehen?“) oder wenn jemand von 1998 spricht, packst du aus. Dann erzählst du auch, wie der Graf damals den Kelch gefüllt hat. Mach daraus einen großen Moment.",
  ziel="Nicht für die Mörderin gehalten werden. Und endlich die Wahrheit über 1998 loswerden.",
  motiv_kurz="Fristlose Kündigung und öffentliche Drohung („Das werden Sie bereuen!“).",
 ),
 dict(
  id="baptiste", nr=5, kern=True, name="Baptiste Morrow", alter=66,
  titel="Butler des Hauses Rabenstein",
  kostuem="Mumien-Butler: Frack, über den Mullbinden gewickelt sind, weiße Handschuhe, Serviette überm Arm.",
  oeffentlich="Seit 42 Jahren im Dienst der Rabensteins. Diskret, makellose Manieren. Du weißt, wo jede Flasche liegt und wer wann wo war.",
  verhaeltnis="Du dientest dem Grafen stets loyal, auch wenn er ein schwieriger Mann war.",
  geheimnis="""Seit Jahren verkaufst du heimlich einzelne Flaschen aus dem Weinkeller, um die Pflegekosten deiner kranken Schwester zu bezahlen. Der Graf hat es gestern bemerkt und gesagt: <i>„Wir reden nach dem Essen.“</i>""",
  abend_wahr="21:00 füllst du den Blutkelch mit Rotwein aus der Karaffe, 21:05 stellst du ihn auf die Anrichte im Rittersaal. Der Graf läutet nach dir, schickt dich ins Rauchzimmer, um Zigarren und Cognac zu holen („Ich möchte ungestört telefonieren“). Um 21:20 bist du zurück und trägst den Kelch an den Platz des Grafen. Er wirkte unverändert.",
  abend_version="Die Wahrheit, aber ohne den Weinkeller zu erwähnen.",
  beobachtung=[
   "<b>Zeitablauf:</b> Kelch gefüllt 21:00, auf der Anrichte 21:05, Rückkehr 21:20. In diesen 15 Minuten war er <b>unbeaufsichtigt</b>. Davor und danach trank nur der Graf daraus.",
   "Das Gichtliniment (enthält Eisenhut), das Dr. Stein dem Grafen verschrieben hat, steht im Arbeitszimmer. Die Flasche ist <b>voll, das Siegel unversehrt</b>.",
   "1998, als Albrecht von Rabenstein starb, war es <b>Dr. Stein</b>, der den Totenschein ausstellte („Herzversagen“). Du hast das nie hinterfragt. (Nenne das in Runde 2.)",
   "Der Graf wirkte seit Tagen „wie ein Mann, der seinen Frieden macht“.",
  ],
  runde2="Du bist die Quelle für den Zeitablauf. Sag ihn klar und gut hörbar. Dein Weinkeller-Geheimnis kommt heraus, wenn jemand erwähnt, dass im Keller Flaschen fehlen (Lucian war dort).",
  ziel="Dem Haus Rabenstein ein letztes Mal dienen: die Wahrheit über den Tod deines Herrn herausfinden.",
  motiv_kurz="Der Graf hatte den Weinhandel bemerkt („Wir reden nach dem Essen“). Er trug den Kelch (Gelegenheit).",
 ),
 dict(
  id="lucian", nr=6, kern=True, name="Lucian von Rabenstein", alter=31,
  titel="Neffe des Grafen, Sohn von Albrecht († 1998)",
  kostuem="Werwolf: Fellweste, zerrissenes Hemd, Ohren oder Maske, Kunstblut.",
  oeffentlich="Charmant, unruhig, trinkfreudig. Bruder von Rosalie. Du giltst als Haupterbe des Grafen.",
  verhaeltnis="Der Graf hat dich und deine Schwester nach dem Tod eurer Eltern großgezogen: streng, aber stets präsent.",
  geheimnis="""Du hast <b>200.000 € Spielschulden</b>, die Gläubiger drohen. Heute drohte dir der Graf mit Enterbung. Zwischen 20:50 und 21:05 habt ihr im Arbeitszimmer laut gestritten. Du brülltest: <i>„Ich weiß, was du Papa angetan hast!“</i> Denn du hast letzte Woche in Papas altem Schreibtisch diesen Brief gefunden:<br><i>„Lieber Leopold, ich komme heute Abend zu Deinem Essen, obwohl Du mir meinen Anteil nicht gönnst. Falls mir etwas zustößt: Ich traue Dir nicht mehr. – Albrecht.“</i>""",
  abend_wahr="Nach dem Streit gingst du um 21:05 in den <b>Weinkeller</b> und trankst dort allein eine Flasche. Auf dem Weg dorthin kamst du um <b>21:06</b> am Rittersaal und am Kaminzimmer vorbei: Der Blutkelch stand allein auf der Anrichte, niemand war im Saal. <b>Madame Zora war allein</b> im Kaminzimmer und stellte Kerzen auf. Dr. Stein war nicht bei ihr.",
  abend_version="„Nach dem Streit habe ich frische Luft auf der Terrasse geschnappt.“ (Lüge! Edgar war dort und hat dich nicht gesehen.)",
  beobachtung=[
   "<b>21:06:</b> Rittersaal leer, Kelch allein auf der Anrichte. Zora allein im Kaminzimmer, <b>Dr. Stein nicht bei ihr</b>.",
   "Der Streit: Der Graf sagte am Ende: <i>„Heute Nacht wirst du verstehen, warum ich so hart war. Um Mitternacht wird alles gesagt.“</i>",
   "Der Brief von Albrecht (siehe Geheimnis). Zeige ihn in Runde 2.",
  ],
  runde2="Wenn Edgar oder jemand deine Terrassen-Lüge auffliegen lässt, gestehst du den Weinkeller. Dann kannst du Zora entlasten und Stein belasten. Zeige den Brief, wenn jemand 1998 erwähnt.",
  ziel="Beweisen, dass du nicht der Mörder bist, und herausfinden, ob der Graf deinen Vater getötet hat.",
  motiv_kurz="Schulden, Drohung mit Enterbung, lauter Streit mit Todesdrohung-Tonfall.",
 ),
 dict(
  id="morgana", nr=7, kern=True, name="Gräfin Morgana von Rabenstein", alter=48,
  titel="Zweite Frau des Grafen",
  kostuem="Vampirin: schwarzes oder dunkelrotes Abendkleid, Stehkragen-Umhang, Fangzähne.",
  oeffentlich="Seit zwölf Jahren Gräfin: elegant, kühl, perfekt frisiert. Du spielst an der Seite des Grafen die Schlossherrin.",
  verhaeltnis="Die Ehe ist längst erkaltet. Man sieht euch selten zusammen, außer bei Festen.",
  geheimnis="""Vor einer Woche hast du mit einem Scheidungsanwalt gesprochen. Ergebnis: Im Ehevertrag steht, dass du bei einer Scheidung <b>nichts</b> bekommst. Als <b>Witwe</b> aber erbst du das lebenslange Wohnrecht und ein Vermögen. Du hast heute Abend heimlich einen <b>Koffer gepackt</b> und wolltest nach dem Essen verschwinden. Niemand darf das wissen: Es sieht aus wie ein perfektes Mordmotiv.""",
  abend_wahr="21:00 bis 21:18 in deinen Gemächern im Obergeschoss, allein beim Kofferpacken. Gegen <b>21:11</b> tratest du auf die Galerie und sahst hinunter: Eine Gestalt in <b>schwarzem Umhang mit schwarzen Handschuhen</b> verließ eilig den Rittersaal in Richtung Halle. Ein Gesicht hast du nicht gesehen, du dachtest an Dimitri.",
  abend_version="„Ich habe in der Bibliothek gelesen.“ (Lüge! Lilith war dort und hat dich nicht gesehen.)",
  beobachtung=[
   "<b>21:11:</b> schwarzer Umhang, schwarze Handschuhe, eilig aus dem Rittersaal in die Halle. Kein Gesicht.",
   "Der Graf sagte gestern zu dir: <i>„Morgen ist alles vorbei, für uns alle.“</i>",
   "Dein gepackter Koffer steht in deinem Zimmer.",
  ],
  runde2="Wenn deine Bibliotheks-Lüge auffliegt, gib zu, oben gewesen zu sein, aber nicht den Koffer. Der kommt erst raus, wenn man dich direkt danach fragt oder wenn die SL „Durchsuchung“ ruft.",
  ziel="Nicht verdächtigt werden. Heimlich möchtest du wissen, ob du erbst.",
  motiv_kurz="Erbe als Witwe; heimlich gepackter Koffer (Fluchtplan).",
 ),
 dict(
  id="agatha", nr=8, kern=False, name="Agatha Grimm", alter=45,
  titel="Bestseller-Autorin von Gruselkrimis",
  kostuem="Schwarze Witwe: schwarzes Kleid, Spinnennetz-Schal, Spinnen-Brosche.",
  oeffentlich="Autorin der Reihe „Die Toten von Moorhall“. Scharfzüngig und neugierig. Der Graf hat dich „zur Inspiration“ eingeladen.",
  verhaeltnis="Du schreibst, so heißt es, einen Roman, der auf Schloss Rabenstein spielt.",
  geheimnis="""In Wahrheit recherchierst du für eine <b>Enthüllungsbiografie</b> über den Grafen. Du hast dir heimlich Zugang zum Turmarchiv verschafft. Der Graf hat es heute entdeckt und gedroht, dich zu verklagen und deine Karriere zu zerstören.""",
  abend_wahr="21:00 bis 21:20 im <b>Turmarchiv</b>. Du fandest die Mappe <b>„Albrecht 1998“</b> mit der Kopie eines Totenscheins (ausgestellt von Dr. med. V. Stein), einem Zeitungsausschnitt und einer Quittung über 50.000 DM „für besondere Diskretion“, Empfänger „V. S.“.",
  abend_version="„Ich saß im Salon und habe Notizen gemacht.“",
  beobachtung=[
   "<b>Die Archivmappe</b> (Hinweiskarte H7). Du legst sie vor, wenn die SL „Archiv!“ ruft, oder früher, wenn man dich unter Druck setzt.",
   "Du bist die Expertin für Gifte: <b>Aconitin</b> (Eisenhut) wirkt nach 10 bis 60 Minuten (Kribbeln, Taubheit, Herzrhythmusstörungen). Eine <b>Tinktur</b> ist ein hochkonzentrierter Alkoholauszug, der im Rotwein kaum auffällt. Rohe Pflanzenteile hätte man gesehen oder geschmeckt.",
  ],
  runde2="Du darfst Fachwissen einstreuen und die Gruppe zu den richtigen Fragen führen, aber deine eigene Spionage-Geschichte kommt erst heraus, wenn man dir die Mappe nachweist.",
  ziel="Den Fall lösen (das wird dein bester Roman!) und deinen Ruf als Autorin bewahren.",
  motiv_kurz="Der Graf drohte, sie zu verklagen und ihre Karriere zu zerstören.",
 ),
 dict(
  id="lilith", nr=9, kern=False, name="Lilith Schwarz", alter=34,
  titel="Privatsekretärin & Buchhalterin des Grafen",
  kostuem="Geist („Weiße Frau“): weißes Kleid oder Laken, blasse Schminke, offene Haare.",
  oeffentlich="Seit sieben Jahren organisierst du alles für den Grafen: Termine, Konten, Korrespondenz. Still, effizient, immer mit Notizblock.",
  verhaeltnis="Du kennst jedes Geheimnis im Haus, zumindest auf Papier.",
  geheimnis="""Du hast in drei Jahren <b>40.000 €</b> auf ein eigenes Konto abgezweigt. Der Graf hat es bemerkt: <i>„Wir rechnen um Mitternacht ab.“</i>""",
  abend_wahr="Um 20:50 hörtest du aus dem Arbeitszimmer den Streit zwischen Lucian und dem Grafen. Von 21:00 bis 21:20 warst du in der <b>Bibliothek</b> und hast Belege kopiert und vernichtet. Du warst die ganze Zeit allein. <b>Niemand kam in die Bibliothek</b>, weder Gräfin Morgana noch sonst jemand.",
  abend_version="„Ich habe in der Bibliothek Termine für morgen sortiert.“ (Ort stimmt, Tätigkeit nicht.)",
  beobachtung=[
   "<b>Streit 20:50 bis 21:05:</b> Lucian brüllte: <i>„Ich weiß, was du Papa angetan hast!“</i> Der Graf: <i>„Dann weißt du auch, warum heute Schluss ist. Um Mitternacht wird alles gesagt.“</i>",
   "<b>Bibliothek 21:00 bis 21:20:</b> Du warst allein. Wer behauptet, dort gewesen zu sein, lügt.",
   "Der Graf ließ vorgestern seinen <b>Notar</b> anrufen: Er wollte das Testament ändern. Du weißt nicht, wie.",
  ],
  runde2="Wenn jemand behauptet, in der Bibliothek gewesen zu sein, sagst du klar: „Das stimmt nicht, ich war allein dort.“ Dein Unterschlagungs-Geheimnis bleibt, bis jemand die Buchhaltung erwähnt.",
  ziel="Schadensbegrenzung: Du willst nicht, dass deine Veruntreuung auffliegt, aber auch nicht für den Mord büßen.",
  motiv_kurz="Veruntreuung entdeckt; „Abrechnung um Mitternacht“.",
 ),
 dict(
  id="jack", nr=10, kern=False, name="Jack Kürbiss", alter=29,
  titel="Gärtner & Hausmeister",
  kostuem="Vogelscheuche: Flickenhemd, Strohhut, Stroh an den Ärmeln, Gartenhandschuhe.",
  oeffentlich="Seit sechs Jahren Gärtner. Der Kürbisgarten und das Gewächshaus sind dein Reich. Wortkarg, verlässlich, riechst nach Erde.",
  verhaeltnis="Der Graf ist ein strenger Chef, der dich gern „Dreckschaufler“ nennt.",
  geheimnis="""Du und <b>Rosalie</b> seid ein heimliches Paar. Der Graf hat euch gestern erwischt und gedroht, dich zu feuern und Rosalie „nach Übersee“ zu schicken. Außerdem züchtest du im Gewächshaus <b>Blauen Eisenhut</b> (14 Pflanzen, für das Giftpflanzenbeet im Schlossgarten, auf Wunsch des Grafen).""",
  abend_wahr="21:00 bis 21:20 im <b>Gewächshaus mit Rosalie</b>. Ihr habt euch geküsst und über Flucht geredet.",
  abend_version="„Ich war allein im Gewächshaus und habe Kürbisse geerntet.“ (Halb gelogen: Rosalie war bei dir.)",
  beobachtung=[
   "Um 21:20 hast du wie jeden Abend nachgezählt: <b>Alle 14 Eisenhut-Pflanzen</b> sind vollständig, nichts abgeschnitten. Die Gewächshaustür war abgeschlossen. Den Schlüssel hast nur du.",
   "Rosalie und du seid gegenseitig euer Alibi, sobald ihr eure Beziehung zugebt.",
  ],
  runde2="Wenn man dich wegen des Eisenhuts verdächtigt, wirst du laut (zu Recht!). Gestehe die Beziehung zu Rosalie, wenn sie in Verdacht gerät oder du in die Enge getrieben wirst.",
  ziel="Eure Liebe schützen und beweisen, dass der Eisenhut nicht aus deinem Gewächshaus stammt.",
  motiv_kurz="Rauswurf und Trennung von Rosalie angedroht; Zugang zu Eisenhut.",
 ),
 dict(
  id="rosalie", nr=11, kern=False, name="Rosalie von Rabenstein", alter=28,
  titel="Nichte & Mündel des Grafen, Kunstrestauratorin",
  kostuem="Rabenmädchen: schwarzes Kleid mit Federn, <b>Schnabel-Halbmaske</b> (hängt um den Hals).",
  oeffentlich="Lucians jüngere Schwester. Träumerisch, sensibel, immer mit Skizzenbuch. Heute bist du der „Rabe von Rabenstein“.",
  verhaeltnis="Dein Vormund, der Graf, hat dich großgezogen. Du liebst ihn und fürchtest ihn.",
  geheimnis="""Du bist heimlich mit dem Gärtner <b>Jack</b> zusammen. Gestern hat euch der Graf erwischt und gedroht, dich nach Übersee zu schicken. Wenn das rauskommt, bist du erst recht verdächtig.""",
  abend_wahr="21:00 bis 21:20 im <b>Gewächshaus bei Jack</b>. Auf dem Rückweg gegen <b>21:19</b> sahst du in der Halle <b>Dr. Stein</b>, der hastig seine schwarzen Lederhandschuhe auszog und in die Arzttasche stopfte. Er roch seltsam bitter und wirkte nervös. Er sagte nur „Guten Abend, Fräulein.“",
  abend_version="„Ich habe in der Bibliothek gelesen.“ (Lüge! Lilith war allein dort.)",
  beobachtung=[
   "<b>21:19:</b> Dr. Stein steckt in der Halle hastig schwarze Handschuhe in seine Tasche. Bitterer Geruch, nervös.",
   "Deine Schnabelmaske hing den ganzen Abend um deinen Hals. Andere könnten Verdacht schöpfen, weil ein „Schnabel“ gesehen wurde.",
  ],
  runde2="Wenn jemand den „Schnabel“ erwähnt, wirst du nervös. Beweise dein Alibi mit Jack. Nenne dann, was du bei Stein gesehen hast.",
  ziel="Dein Alibi (und eure Liebe) retten, ohne dass Jack ins Visier gerät.",
  motiv_kurz="Der Graf wollte sie von Jack trennen; trägt eine Schnabelmaske (Verwechslung mit dem „Schnabel-Schatten“).",
 ),
 dict(
  id="pater", nr=12, kern=False, name="Pater Ambrosius", alter=60,
  titel="Hausgeistlicher von Schloss Rabenstein",
  kostuem="Mönch: braune Kutte mit Kapuze, Holzkreuz, Rosenkranz (optional Teufelshörner).",
  oeffentlich="Seit 30 Jahren Seelsorger auf Rabenstein. Friedfertig, belesen, mit trockenem Humor.",
  verhaeltnis="Der Graf beichtet bei dir.",
  geheimnis="""Vor neun Tagen beichtete dir der Graf, dass er seinen Bruder Albrecht vergiftet hat. Das <b>Beichtgeheimnis</b> bindet dich: Du darfst den Inhalt <b>nicht</b> wiederholen. Du darfst nur andeuten, dass der Graf „eine schwere Last ablegen wollte“. Du hast ihm geraten, öffentlich zu bekennen, und fürchtest nun, dass genau das ihn das Leben gekostet hat.""",
  abend_wahr="21:00 bis 21:20 in der Kapelle und in der <b>Krypta, zusammen mit Graf Dimitri</b>. Du hast ihn dabei ertappt, wie er in der Krypta etwas suchte. Ihr habt euch lange unterhalten.",
  abend_version="„Ich habe in der Kapelle gebetet.“ (Dimitri war bei dir, das verschweigst du.)",
  beobachtung=[
   "Der Graf sagte am Nachmittag: <i>„Heute Nacht wird mir ein Stein vom Herzen fallen.“</i>",
   "Du hast Albrecht 1998 beerdigt. Im Kirchenbuch steht „Herzversagen“, so wie es auf dem Totenschein stand.",
   "Dimitri und du habt euch gegenseitig als Alibi.",
  ],
  runde2="Du darfst Hinweise geben wie „Der Graf war ein Mann, der seinen Frieden suchte“, aber niemals den Inhalt der Beichte aussprechen. Das Spannende: Man darf dich bedrängen, aber du bleibst standhaft.",
  ziel="Das Beichtgeheimnis wahren und trotzdem helfen, den Mörder zu finden.",
  motiv_kurz="Der Graf beichtete ihm; Spielraum für Gewissenskonflikt, aber kaum Motiv.",
 ),
 dict(
  id="dimitri", nr=13, kern=False, name="Graf Dimitri Vlad", alter=57,
  titel="Nachbar jenseits des Moors & Jagdrivale",
  kostuem="Vampir: schwarzer Umhang mit Stehkragen, Dracula-Look, Fangzähne.",
  oeffentlich="Gutsbesitzer, höflich bis zur Schmerzgrenze. Eure Familien streiten seit Generationen um Land und Ehre.",
  verhaeltnis="Der Graf hat dich zur „Versöhnung“ eingeladen. Du bist skeptisch.",
  geheimnis="""Der Graf besitzt seit 1995 deinen Familienschatz, den <b>Blutrubin</b>, den er dir beim Kartenspiel abgeluchst hat – ein Betrug, sagst du. Du glaubst, er liegt in der Krypta der Rabensteins, und wolltest ihn heute Abend heimlich holen.""",
  abend_wahr="21:00 bis 21:20 in der Krypta. <b>Pater Ambrosius</b> hat dich ertappt, ihr seid zusammen geblieben. Um 21:21 kamst du in die Halle und sahst Baptiste, der den Kelch zum Platz des Grafen trug.",
  abend_version="„Ich bin im Park spazieren gegangen, die Nacht ist so schön.“",
  beobachtung=[
   "Der Graf sagte gestern beim Aperitif: <i>„Du bekommst, was dir gehört, Dimitri. Nach Mitternacht.“</i>",
   "Dein schwarzer Umhang ist verdächtig, aber du hast ein Alibi mit Pater Ambrosius.",
   "21:21: Baptiste trägt den Kelch in den Saal. Er sieht aus wie immer.",
  ],
  runde2="Dein Alibi hängt an Pater Ambrosius. Wenn du in die Enge getrieben wirst, gesteh die Krypta und den Rubin.",
  ziel="Deinen Besitz zurückbekommen, ohne verdächtigt zu werden.",
  motiv_kurz="Alter Streit um Land und den Blutrubin; schwarzer Umhang.",
 ),
]

# Beweiskarten (Hinweiskarten)
HINWEISE = [
 dict(id="H1", runde=1, titel="Befund: Der Blutkelch",
  text="Im Rest des Weins im umgekippten Kelch wurde <b>Tinctura Aconiti</b> nachgewiesen – Eisenhut-Tinktur, hochkonzentriert (ein Alkoholauszug). Aconitin wirkt binnen 10 bis 60 Minuten: Kribbeln, Taubheit, Herzrhythmusstörungen, Herzstillstand. Wein überdeckt den bitteren Geschmack. <b>Pflanzenreste wurden nicht gefunden.</b>"),
 dict(id="H2", runde=1, titel="Fundstück: Die leere Phiole",
  text="Hinter dem schweren Vorhang neben der Anrichte im Rittersaal liegt eine kleine <b>braune Glasphiole</b> (5 ml), leer, Geruch bitter. Vom Etikett ist nur ein Rest lesbar: <i>„…ura Aconiti – Nur zur äußerlichen Anwendung! – Apotheke Schwarzmoor“</i>."),
 dict(id="H3", runde=1, titel="Fundstück: Zettel des Grafen (Teil 1)",
  text="In der Jackentasche des Toten, in seiner Handschrift: <i>„Um Mitternacht werde ich beichten. Was 1998 mit Albrecht geschah, war kein Herzversagen. Ich trage die Schuld – aber ich war nicht allein. Heute Nacht endet das Schweigen.“</i>"),
 dict(id="H4", runde=1, titel="Zeitablauf des Abends",
  text="""<table class="zeit"><tr><td>20:00</td><td>Beginn des Banketts im Rittersaal</td></tr>
  <tr><td>21:00</td><td>Pause zwischen den Gängen. Baptiste füllt den Blutkelch. Die Gäste verteilen sich im Schloss.</td></tr>
  <tr><td>21:05</td><td>Der Graf läutet nach Baptiste. Der Kelch steht <b>allein auf der Anrichte</b> im Rittersaal.</td></tr>
  <tr><td>21:20</td><td>Baptiste kehrt zurück und stellt den Kelch an den Platz des Grafen.</td></tr>
  <tr><td>21:30</td><td>Toast des Grafen. Er trinkt aus dem Blutkelch.</td></tr>
  <tr><td>21:35</td><td>Madame Zora löscht die Kerzen: Beginn der Séance.</td></tr>
  <tr><td>21:45</td><td>Ein Schrei. Als das Licht wieder brennt, ist der Graf tot.</td></tr></table>
  <p class="klein"><b>Tatzeitfenster: 21:05 bis 21:20.</b></p>"""),
 dict(id="H5", runde=2, titel="Fundstück: Zettel des Grafen (Teil 2)",
  text="Zerknüllt im Papierkorb des Arbeitszimmers: <i>„…Wer damals den Totenschein unterschrieb, hat 25 Jahre gut von meinem Schweigen gelebt. Dieser Mensch wird nicht wollen, dass ich rede. Ich habe ihn gewarnt – vielleicht war das mein Fehler.“</i>"),
 dict(id="H6", runde=2, titel="Inventur des Inspektors",
  text="<b>Gewächshaus:</b> Alle 14 Eisenhut-Pflanzen sind vollständig, Tür verschlossen, Schlüssel nur beim Gärtner.<br><b>Séance-Koffer von Madame Zora:</b> Ein Bündel getrockneter Eisenhutwurzel, original verschnürt, unangetastet.<br><b>Arbeitszimmer des Grafen:</b> Gichtliniment-Flasche voll, Siegel unversehrt.<br><b>Ergebnis:</b> Die Tinktur stammt weder aus dem Garten noch aus Zoras Koffer noch aus dem Vorrat des Grafen."),
 dict(id="H7", runde=3, titel="Archivmappe „Albrecht 1998“",
  text="<b>Totenbescheinigung:</b> Albrecht von Rabenstein, † 31.10.1998. Todesursache: Herzversagen. Ausgestellt von: <b>Dr. med. V. Stein</b>.<br><b>Zeitungsausschnitt:</b> „Tragischer Tod auf Schloss Rabenstein.“<br><b>Quittung vom 02.11.1998:</b> „50.000 DM – für besondere Diskretion. Empfänger: V. S.“<br><span class='klein'>(Gebt diese Karte, wenn die SL „Archiv!“ ruft, oder wenn Agatha Grimm sie vorlegt.)</span>"),
]
